-- +migrate Up
CREATE TABLE wallet (
    wallet_id UUID NOT NULL PRIMARY KEY,
    owner VARCHAR NOT NULL,
    balance NUMERIC(16, 2) NOT NULL DEFAULT 0,
    currency VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
