version: '3.8'

services:
  pg:
    image: postgres:latest
    container_name: web-service_pg
    environment:
      POSTGRES_DB: web-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    command: ['postgres', '-c', 'log_statement=all']
