version: '3.8'

services:
  pg:
    image: postgres:latest
    container_name: wallets-service_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    command: ['postgres', '-c', 'log_statement=all']

  xr:
    build:
      dockerfile: deploy/exchange-rate/Dockerfile
      context: .
    container_name: exchange-rate_stub
    ports:
      - '8091:8091'


